[package]
name = "korg_nano_kontrol_2"
version = "0.1.0"
authors = ["JoshuaBatty <joshpbatty@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.5"
